include("/home/nuc/code/PassIt/cmake/CPM.cmake")
CPMAddPackage("NAME;freetype;GITHUB_REPOSITORY;freetype/freetype;GIT_TAG;VER-2-13-2;OPTIONS;FT_DISABLE_ZLIB ON;FT_DISABLE_BZIP2 ON;FT_DISABLE_PNG ON;FT_DISABLE_HARFBUZZ ON;FT_DISABLE_BROTLI ON;BUILD_SHARED_LIBS OFF")
set(freetype_FOUND TRUE)